name: Create Monthly Ranking

on:
  workflow_dispatch:

jobs:
  create_monthly_ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          bash aa_month.sh
