name: Create Monthly Ranking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 28-31 * SUN'
    # -> 毎月1日と月曜日のUTC15:00（JST0:00,深夜）に実行。
    #    とにかく毎月1日の0:00には確実に実行したいから、ざっくり28-31でやる。

env:
  QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
  TZ: 'Asia/Tokyo'

jobs:
  create_monthly_ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          echo $TZ
          date
          bash aa_month.sh
          git config --global user.name "matt-note"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "From GitHub Actions..." || echo "No changes to commit"
          git push
