name: Create Monthly Ranking

on:
  workflow_dispatch:

jobs:
  create_monthly_ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash aa_month.sh
          cat month.csv
          git config --global user.name "matt-note"
          git config --global user.email "${{ secrets.EMAIL }}"
          git commit -am "From GitHub Actions..."
          git push
