name: Create Monthly Ranking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
    # -> 毎日 UTC15:00（JST0:00,深夜）に実行。

env:
  QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
  # TZ: 'Asia/Tokyo'
  # -> これを設定してもGitHub ActionsはUTCで実行する。

jobs:
  create_monthly_ranking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          bash aa_month.sh
          git config --global user.name "matt-note"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "From GitHub Actions..." || echo "No changes to commit"
          git push
